# Generated by Django 2.0 on 2018-09-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='day_length',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='year_length',
        ),
    ]
